name: Multiarch build

on:
  push:
    branches: 'main'

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
        
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/cafsenra/synology-csi/synology-csi
          tags: v1.0.0
          archs: amd64, arm64
          dockerfiles: |
            ./Dockerfile
            
      - name: Push docker image
        run: |
          echo $TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/cafsenra/synology-csi/synology-csi:v1.0.0
        env:
          TOKEN: ${{ secrets.DOCKER_PUSH }}

      - name: Print image url
        run: echo "Image pushed ghcr.io/cafsenra/synology-csi/synology-csi:v1.0.0"
